name: esc_pos_bluetooth_plus
description: The library allows to print receipts using an ESC/POS thermal Bluetooth printer.
version: 0.4.1
homepage: https://github.com/e-ManueI/esc_pos_bluetooth_plus
publish_to: none

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.0
  esc_pos_utils_plus: ^2.0.1+6
  flutter_bluetooth_basic_updated: 
    git:
      url: https://github.com/CidQu/flutter_bluetooth_basic/

dev_dependencies:
  flutter_test:
    sdk: flutter
